/* Chatulileo — Seed vocabulary
 * ~150 curated cards spanning A1–B1.
 * Personal study only. Source material: Lagune 1, Lagune 3, Schwache Verben, Bellingua A2 Modul 16.
 *
 * Card schemas:
 *
 * Noun:
 *   { id, type: 'noun', article: 'der'|'die'|'das', word, plural, en: [..],
 *     example: { de, en }, level: 'A1'|'A2'|'B1' }
 *
 * Verb:
 *   { id, type: 'verb', infinitive, en: [..],
 *     conj: { ich, du, er, wir, ihr, sie },
 *     perfekt, praeteritum, hilfsverb: 'haben'|'sein',
 *     reflexive: bool, separable: bool, strong: bool,
 *     objectCase: null|'Akk'|'Dat',
 *     prepositions: [{ prep, case: 'Akk'|'Dat', meaning }],
 *     example: { de, en }, level }
 *
 * Example sentence markup for case coloring:
 *   [prep|case]phrase[/]   e.g. [bei|dat]dir[/]
 *   [verb|case]phrase[/]   for verb-forced cases  e.g. [verb|dat]dir[/]
 */

const SEED_CARDS = [
  /* ========== NOUNS — A1 ========== */
  { id: 's_n_001', type: 'noun', article: 'der', word: 'Hund', plural: 'Hunde', en: ['dog'], example: { de: 'Der Hund schläft auf dem Sofa.', en: 'The dog is sleeping on the sofa.' }, level: 'A1' },
  { id: 's_n_002', type: 'noun', article: 'die', word: 'Katze', plural: 'Katzen', en: ['cat'], example: { de: 'Die Katze trinkt Milch.', en: 'The cat is drinking milk.' }, level: 'A1' },
  { id: 's_n_003', type: 'noun', article: 'das', word: 'Haus', plural: 'Häuser', en: ['house'], example: { de: 'Das Haus ist groß.', en: 'The house is big.' }, level: 'A1' },
  { id: 's_n_004', type: 'noun', article: 'die', word: 'Wohnung', plural: 'Wohnungen', en: ['apartment', 'flat'], example: { de: 'Meine Wohnung hat drei Zimmer.', en: 'My apartment has three rooms.' }, level: 'A1' },
  { id: 's_n_005', type: 'noun', article: 'das', word: 'Zimmer', plural: 'Zimmer', en: ['room'], example: { de: 'Das Zimmer ist klein.', en: 'The room is small.' }, level: 'A1' },
  { id: 's_n_006', type: 'noun', article: 'die', word: 'Küche', plural: 'Küchen', en: ['kitchen'], example: { de: 'In der Küche kocht meine Mutter.', en: 'My mother is cooking in the kitchen.' }, level: 'A1' },
  { id: 's_n_007', type: 'noun', article: 'das', word: 'Bad', plural: 'Bäder', en: ['bathroom'], example: { de: 'Das Bad ist neu.', en: 'The bathroom is new.' }, level: 'A1' },
  { id: 's_n_008', type: 'noun', article: 'der', word: 'Tisch', plural: 'Tische', en: ['table'], example: { de: 'Der Tisch steht in der Mitte.', en: 'The table is in the middle.' }, level: 'A1' },
  { id: 's_n_009', type: 'noun', article: 'der', word: 'Stuhl', plural: 'Stühle', en: ['chair'], example: { de: 'Der Stuhl ist aus Holz.', en: 'The chair is made of wood.' }, level: 'A1' },
  { id: 's_n_010', type: 'noun', article: 'das', word: 'Bett', plural: 'Betten', en: ['bed'], example: { de: 'Das Bett ist sehr bequem.', en: 'The bed is very comfortable.' }, level: 'A1' },
  { id: 's_n_011', type: 'noun', article: 'die', word: 'Lampe', plural: 'Lampen', en: ['lamp'], example: { de: 'Die Lampe gibt warmes Licht.', en: 'The lamp gives warm light.' }, level: 'A1' },
  { id: 's_n_012', type: 'noun', article: 'das', word: 'Fenster', plural: 'Fenster', en: ['window'], example: { de: 'Das Fenster ist offen.', en: 'The window is open.' }, level: 'A1' },
  { id: 's_n_013', type: 'noun', article: 'die', word: 'Tür', plural: 'Türen', en: ['door'], example: { de: 'Die Tür ist geschlossen.', en: 'The door is closed.' }, level: 'A1' },
  { id: 's_n_014', type: 'noun', article: 'der', word: 'Mann', plural: 'Männer', en: ['man'], example: { de: 'Der Mann liest Zeitung.', en: 'The man is reading the newspaper.' }, level: 'A1' },
  { id: 's_n_015', type: 'noun', article: 'die', word: 'Frau', plural: 'Frauen', en: ['woman'], example: { de: 'Die Frau arbeitet als Lehrerin.', en: 'The woman works as a teacher.' }, level: 'A1' },
  { id: 's_n_016', type: 'noun', article: 'das', word: 'Kind', plural: 'Kinder', en: ['child'], example: { de: 'Das Kind spielt im Garten.', en: 'The child is playing in the garden.' }, level: 'A1' },
  { id: 's_n_017', type: 'noun', article: 'der', word: 'Vater', plural: 'Väter', en: ['father'], example: { de: 'Mein Vater kommt aus Deutschland.', en: 'My father is from Germany.' }, level: 'A1' },
  { id: 's_n_018', type: 'noun', article: 'die', word: 'Mutter', plural: 'Mütter', en: ['mother'], example: { de: 'Meine Mutter heißt Anna.', en: "My mother's name is Anna." }, level: 'A1' },
  { id: 's_n_019', type: 'noun', article: 'der', word: 'Bruder', plural: 'Brüder', en: ['brother'], example: { de: 'Mein Bruder ist älter als ich.', en: 'My brother is older than me.' }, level: 'A1' },
  { id: 's_n_020', type: 'noun', article: 'die', word: 'Schwester', plural: 'Schwestern', en: ['sister'], example: { de: 'Meine Schwester wohnt in Berlin.', en: 'My sister lives in Berlin.' }, level: 'A1' },
  { id: 's_n_021', type: 'noun', article: 'der', word: 'Freund', plural: 'Freunde', en: ['friend (m)', 'boyfriend'], example: { de: 'Mein Freund kommt heute Abend.', en: 'My friend is coming tonight.' }, level: 'A1' },
  { id: 's_n_022', type: 'noun', article: 'die', word: 'Freundin', plural: 'Freundinnen', en: ['friend (f)', 'girlfriend'], example: { de: 'Meine Freundin spielt Klavier.', en: 'My friend plays piano.' }, level: 'A1' },
  { id: 's_n_023', type: 'noun', article: 'das', word: 'Buch', plural: 'Bücher', en: ['book'], example: { de: 'Das Buch ist sehr interessant.', en: 'The book is very interesting.' }, level: 'A1' },
  { id: 's_n_024', type: 'noun', article: 'die', word: 'Zeitung', plural: 'Zeitungen', en: ['newspaper'], example: { de: 'Ich lese jeden Morgen die Zeitung.', en: 'I read the newspaper every morning.' }, level: 'A1' },
  { id: 's_n_025', type: 'noun', article: 'der', word: 'Stift', plural: 'Stifte', en: ['pen'], example: { de: 'Hast du einen Stift für mich?', en: 'Do you have a pen for me?' }, level: 'A1' },
  { id: 's_n_026', type: 'noun', article: 'das', word: 'Heft', plural: 'Hefte', en: ['notebook'], example: { de: 'Das Heft liegt auf dem Tisch.', en: 'The notebook is on the table.' }, level: 'A1' },
  { id: 's_n_027', type: 'noun', article: 'die', word: 'Schule', plural: 'Schulen', en: ['school'], example: { de: 'Die Schule beginnt um acht.', en: 'School starts at eight.' }, level: 'A1' },
  { id: 's_n_028', type: 'noun', article: 'die', word: 'Universität', plural: 'Universitäten', en: ['university'], example: { de: 'Sie studiert an der Universität.', en: 'She studies at the university.' }, level: 'A1' },
  { id: 's_n_029', type: 'noun', article: 'der', word: 'Lehrer', plural: 'Lehrer', en: ['teacher (m)'], example: { de: 'Der Lehrer erklärt die Grammatik.', en: 'The teacher explains the grammar.' }, level: 'A1' },
  { id: 's_n_030', type: 'noun', article: 'die', word: 'Lehrerin', plural: 'Lehrerinnen', en: ['teacher (f)'], example: { de: 'Die Lehrerin ist sehr nett.', en: 'The teacher is very nice.' }, level: 'A1' },
  { id: 's_n_031', type: 'noun', article: 'der', word: 'Schüler', plural: 'Schüler', en: ['pupil', 'student'], example: { de: 'Der Schüler macht Hausaufgaben.', en: 'The pupil is doing homework.' }, level: 'A1' },
  { id: 's_n_032', type: 'noun', article: 'der', word: 'Tag', plural: 'Tage', en: ['day'], example: { de: 'Heute ist ein schöner Tag.', en: "Today is a beautiful day." }, level: 'A1' },
  { id: 's_n_033', type: 'noun', article: 'die', word: 'Nacht', plural: 'Nächte', en: ['night'], example: { de: 'Die Nacht war sehr ruhig.', en: 'The night was very quiet.' }, level: 'A1' },
  { id: 's_n_034', type: 'noun', article: 'der', word: 'Morgen', plural: 'Morgen', en: ['morning'], example: { de: 'Am Morgen trinke ich Kaffee.', en: 'In the morning I drink coffee.' }, level: 'A1' },
  { id: 's_n_035', type: 'noun', article: 'der', word: 'Abend', plural: 'Abende', en: ['evening'], example: { de: 'Am Abend lese ich oft.', en: 'In the evening I often read.' }, level: 'A1' },
  { id: 's_n_036', type: 'noun', article: 'die', word: 'Woche', plural: 'Wochen', en: ['week'], example: { de: 'Die Woche hat sieben Tage.', en: 'A week has seven days.' }, level: 'A1' },
  { id: 's_n_037', type: 'noun', article: 'der', word: 'Monat', plural: 'Monate', en: ['month'], example: { de: 'Der Monat August ist warm.', en: 'The month of August is warm.' }, level: 'A1' },
  { id: 's_n_038', type: 'noun', article: 'das', word: 'Jahr', plural: 'Jahre', en: ['year'], example: { de: 'Das Jahr hat zwölf Monate.', en: 'A year has twelve months.' }, level: 'A1' },
  { id: 's_n_039', type: 'noun', article: 'die', word: 'Stunde', plural: 'Stunden', en: ['hour'], example: { de: 'Ich warte schon eine Stunde.', en: "I've been waiting for an hour already." }, level: 'A1' },
  { id: 's_n_040', type: 'noun', article: 'die', word: 'Minute', plural: 'Minuten', en: ['minute'], example: { de: 'Eine Minute hat sechzig Sekunden.', en: 'A minute has sixty seconds.' }, level: 'A1' },
  { id: 's_n_041', type: 'noun', article: 'die', word: 'Zeit', plural: 'Zeiten', en: ['time'], example: { de: 'Ich habe keine Zeit.', en: "I don't have time." }, level: 'A1' },
  { id: 's_n_042', type: 'noun', article: 'das', word: 'Wasser', plural: '—', en: ['water'], example: { de: 'Das Wasser ist kalt.', en: 'The water is cold.' }, level: 'A1' },
  { id: 's_n_043', type: 'noun', article: 'der', word: 'Kaffee', plural: 'Kaffees', en: ['coffee'], example: { de: 'Ich trinke gern Kaffee.', en: 'I like to drink coffee.' }, level: 'A1' },
  { id: 's_n_044', type: 'noun', article: 'der', word: 'Tee', plural: 'Tees', en: ['tea'], example: { de: 'Möchtest du einen Tee?', en: 'Would you like a tea?' }, level: 'A1' },
  { id: 's_n_045', type: 'noun', article: 'das', word: 'Brot', plural: 'Brote', en: ['bread'], example: { de: 'Das Brot ist frisch.', en: 'The bread is fresh.' }, level: 'A1' },
  { id: 's_n_046', type: 'noun', article: 'der', word: 'Käse', plural: 'Käse', en: ['cheese'], example: { de: 'Der Käse schmeckt gut.', en: 'The cheese tastes good.' }, level: 'A1' },
  { id: 's_n_047', type: 'noun', article: 'der', word: 'Apfel', plural: 'Äpfel', en: ['apple'], example: { de: 'Ein Apfel pro Tag ist gesund.', en: 'An apple a day is healthy.' }, level: 'A1' },
  { id: 's_n_048', type: 'noun', article: 'die', word: 'Banane', plural: 'Bananen', en: ['banana'], example: { de: 'Die Banane ist gelb.', en: 'The banana is yellow.' }, level: 'A1' },
  { id: 's_n_049', type: 'noun', article: 'das', word: 'Auto', plural: 'Autos', en: ['car'], example: { de: 'Das Auto ist neu.', en: 'The car is new.' }, level: 'A1' },
  { id: 's_n_050', type: 'noun', article: 'der', word: 'Bus', plural: 'Busse', en: ['bus'], example: { de: 'Der Bus kommt gleich.', en: 'The bus is coming soon.' }, level: 'A1' },
  { id: 's_n_051', type: 'noun', article: 'der', word: 'Zug', plural: 'Züge', en: ['train'], example: { de: 'Der Zug fährt um neun.', en: 'The train leaves at nine.' }, level: 'A1' },
  { id: 's_n_052', type: 'noun', article: 'das', word: 'Fahrrad', plural: 'Fahrräder', en: ['bicycle'], example: { de: 'Mein Fahrrad ist blau.', en: 'My bicycle is blue.' }, level: 'A1' },
  { id: 's_n_053', type: 'noun', article: 'die', word: 'Stadt', plural: 'Städte', en: ['city', 'town'], example: { de: 'Die Stadt ist sehr alt.', en: 'The city is very old.' }, level: 'A1' },
  { id: 's_n_054', type: 'noun', article: 'das', word: 'Land', plural: 'Länder', en: ['country', 'land'], example: { de: 'Welches Land magst du am meisten?', en: 'Which country do you like the most?' }, level: 'A1' },
  { id: 's_n_055', type: 'noun', article: 'die', word: 'Straße', plural: 'Straßen', en: ['street'], example: { de: 'Die Straße ist lang.', en: 'The street is long.' }, level: 'A1' },

  /* ========== NOUNS — A2 ========== */
  { id: 's_n_056', type: 'noun', article: 'die', word: 'Arbeit', plural: 'Arbeiten', en: ['work', 'job'], example: { de: 'Die Arbeit macht mir Spaß.', en: 'I enjoy the work.' }, level: 'A2' },
  { id: 's_n_057', type: 'noun', article: 'der', word: 'Beruf', plural: 'Berufe', en: ['profession', 'occupation'], example: { de: 'Was ist dein Beruf?', en: 'What is your profession?' }, level: 'A2' },
  { id: 's_n_058', type: 'noun', article: 'das', word: 'Büro', plural: 'Büros', en: ['office'], example: { de: 'Mein Büro liegt im dritten Stock.', en: 'My office is on the third floor.' }, level: 'A2' },
  { id: 's_n_059', type: 'noun', article: 'die', word: 'Firma', plural: 'Firmen', en: ['company'], example: { de: 'Die Firma ist sehr groß.', en: 'The company is very big.' }, level: 'A2' },
  { id: 's_n_060', type: 'noun', article: 'der', word: 'Chef', plural: 'Chefs', en: ['boss'], example: { de: 'Mein Chef ist heute krank.', en: 'My boss is sick today.' }, level: 'A2' },
  { id: 's_n_061', type: 'noun', article: 'der', word: 'Kollege', plural: 'Kollegen', en: ['colleague (m)'], example: { de: 'Mein Kollege hilft mir oft.', en: 'My colleague often helps me.' }, level: 'A2' },
  { id: 's_n_062', type: 'noun', article: 'das', word: 'Geld', plural: '—', en: ['money'], example: { de: 'Ich habe nicht viel Geld.', en: "I don't have much money." }, level: 'A2' },
  { id: 's_n_063', type: 'noun', article: 'der', word: 'Preis', plural: 'Preise', en: ['price'], example: { de: 'Der Preis ist zu hoch.', en: 'The price is too high.' }, level: 'A2' },
  { id: 's_n_064', type: 'noun', article: 'das', word: 'Geschäft', plural: 'Geschäfte', en: ['shop', 'business'], example: { de: 'Das Geschäft öffnet um zehn.', en: 'The shop opens at ten.' }, level: 'A2' },
  { id: 's_n_065', type: 'noun', article: 'der', word: 'Markt', plural: 'Märkte', en: ['market'], example: { de: 'Auf dem Markt gibt es frisches Obst.', en: 'There is fresh fruit at the market.' }, level: 'A2' },
  { id: 's_n_066', type: 'noun', article: 'das', word: 'Wetter', plural: '—', en: ['weather'], example: { de: 'Das Wetter ist heute schön.', en: 'The weather is nice today.' }, level: 'A2' },
  { id: 's_n_067', type: 'noun', article: 'der', word: 'Regen', plural: '—', en: ['rain'], example: { de: 'Der Regen ist stark.', en: 'The rain is heavy.' }, level: 'A2' },
  { id: 's_n_068', type: 'noun', article: 'die', word: 'Sonne', plural: 'Sonnen', en: ['sun'], example: { de: 'Die Sonne scheint hell.', en: 'The sun is shining brightly.' }, level: 'A2' },
  { id: 's_n_069', type: 'noun', article: 'der', word: 'Schnee', plural: '—', en: ['snow'], example: { de: 'Der Schnee liegt im Garten.', en: 'The snow is lying in the garden.' }, level: 'A2' },
  { id: 's_n_070', type: 'noun', article: 'der', word: 'Wind', plural: 'Winde', en: ['wind'], example: { de: 'Der Wind ist heute kalt.', en: 'The wind is cold today.' }, level: 'A2' },
  { id: 's_n_071', type: 'noun', article: 'die', word: 'Reise', plural: 'Reisen', en: ['trip', 'journey'], example: { de: 'Die Reise war wunderschön.', en: 'The trip was wonderful.' }, level: 'A2' },
  { id: 's_n_072', type: 'noun', article: 'der', word: 'Urlaub', plural: 'Urlaube', en: ['vacation', 'holiday'], example: { de: 'Im Urlaub fahren wir nach Italien.', en: 'On vacation we are going to Italy.' }, level: 'A2' },
  { id: 's_n_073', type: 'noun', article: 'das', word: 'Hotel', plural: 'Hotels', en: ['hotel'], example: { de: 'Das Hotel liegt am Strand.', en: 'The hotel is on the beach.' }, level: 'A2' },
  { id: 's_n_074', type: 'noun', article: 'der', word: 'Strand', plural: 'Strände', en: ['beach'], example: { de: 'Am Strand spielen die Kinder.', en: 'The children are playing on the beach.' }, level: 'A2' },
  { id: 's_n_075', type: 'noun', article: 'das', word: 'Meer', plural: 'Meere', en: ['sea'], example: { de: 'Das Meer ist heute ruhig.', en: 'The sea is calm today.' }, level: 'A2' },
  { id: 's_n_076', type: 'noun', article: 'der', word: 'Berg', plural: 'Berge', en: ['mountain'], example: { de: 'Der Berg ist sehr hoch.', en: 'The mountain is very high.' }, level: 'A2' },
  { id: 's_n_077', type: 'noun', article: 'der', word: 'Wald', plural: 'Wälder', en: ['forest'], example: { de: 'Im Wald ist es ruhig.', en: 'It is quiet in the forest.' }, level: 'A2' },
  { id: 's_n_078', type: 'noun', article: 'der', word: 'Fluss', plural: 'Flüsse', en: ['river'], example: { de: 'Der Fluss fließt durch die Stadt.', en: 'The river flows through the city.' }, level: 'A2' },
  { id: 's_n_079', type: 'noun', article: 'die', word: 'Krankheit', plural: 'Krankheiten', en: ['illness', 'disease'], example: { de: 'Die Krankheit dauert lange.', en: 'The illness lasts a long time.' }, level: 'A2' },
  { id: 's_n_080', type: 'noun', article: 'der', word: 'Arzt', plural: 'Ärzte', en: ['doctor'], example: { de: 'Der Arzt kommt um drei Uhr.', en: 'The doctor is coming at three.' }, level: 'A2' },

  /* ========== NOUNS — B1 ========== */
  { id: 's_n_081', type: 'noun', article: 'die', word: 'Erfahrung', plural: 'Erfahrungen', en: ['experience'], example: { de: 'Diese Erfahrung war sehr wichtig.', en: 'This experience was very important.' }, level: 'B1' },
  { id: 's_n_082', type: 'noun', article: 'die', word: 'Möglichkeit', plural: 'Möglichkeiten', en: ['possibility', 'opportunity'], example: { de: 'Es gibt viele Möglichkeiten.', en: 'There are many possibilities.' }, level: 'B1' },
  { id: 's_n_083', type: 'noun', article: 'die', word: 'Entscheidung', plural: 'Entscheidungen', en: ['decision'], example: { de: 'Die Entscheidung war schwierig.', en: 'The decision was difficult.' }, level: 'B1' },
  { id: 's_n_084', type: 'noun', article: 'die', word: 'Meinung', plural: 'Meinungen', en: ['opinion'], example: { de: 'Was ist deine Meinung dazu?', en: 'What is your opinion on this?' }, level: 'B1' },
  { id: 's_n_085', type: 'noun', article: 'die', word: 'Beziehung', plural: 'Beziehungen', en: ['relationship'], example: { de: 'Unsere Beziehung ist sehr gut.', en: 'Our relationship is very good.' }, level: 'B1' },
  { id: 's_n_086', type: 'noun', article: 'die', word: 'Umwelt', plural: '—', en: ['environment'], example: { de: 'Wir müssen die Umwelt schützen.', en: 'We must protect the environment.' }, level: 'B1' },
  { id: 's_n_087', type: 'noun', article: 'die', word: 'Gesellschaft', plural: 'Gesellschaften', en: ['society'], example: { de: 'Die Gesellschaft verändert sich schnell.', en: 'Society is changing quickly.' }, level: 'B1' },
  { id: 's_n_088', type: 'noun', article: 'der', word: 'Vorteil', plural: 'Vorteile', en: ['advantage'], example: { de: 'Das hat viele Vorteile.', en: 'That has many advantages.' }, level: 'B1' },
  { id: 's_n_089', type: 'noun', article: 'der', word: 'Nachteil', plural: 'Nachteile', en: ['disadvantage'], example: { de: 'Es gibt auch einen Nachteil.', en: 'There is also a disadvantage.' }, level: 'B1' },
  { id: 's_n_090', type: 'noun', article: 'das', word: 'Ziel', plural: 'Ziele', en: ['goal', 'destination'], example: { de: 'Mein Ziel ist es, B1 zu erreichen.', en: 'My goal is to reach B1.' }, level: 'B1' },

  /* ========== VERBS — A1 (regular, no preps) ========== */
  { id: 's_v_001', type: 'verb', infinitive: 'spielen', en: ['to play'],
    conj: { ich: 'spiele', du: 'spielst', er: 'spielt', wir: 'spielen', ihr: 'spielt', sie: 'spielen' },
    perfekt: 'hat gespielt', praeteritum: 'spielte', hilfsverb: 'haben',
    reflexive: false, separable: false, strong: false, objectCase: null, prepositions: [],
    example: { de: 'Die Kinder spielen im Park.', en: 'The children are playing in the park.' }, level: 'A1' },
  { id: 's_v_002', type: 'verb', infinitive: 'lernen', en: ['to learn', 'to study'],
    conj: { ich: 'lerne', du: 'lernst', er: 'lernt', wir: 'lernen', ihr: 'lernt', sie: 'lernen' },
    perfekt: 'hat gelernt', praeteritum: 'lernte', hilfsverb: 'haben',
    reflexive: false, separable: false, strong: false, objectCase: null, prepositions: [],
    example: { de: 'Ich lerne jeden Tag Deutsch.', en: 'I study German every day.' }, level: 'A1' },
  { id: 's_v_003', type: 'verb', infinitive: 'machen', en: ['to do', 'to make'],
    conj: { ich: 'mache', du: 'machst', er: 'macht', wir: 'machen', ihr: 'macht', sie: 'machen' },
    perfekt: 'hat gemacht', praeteritum: 'machte', hilfsverb: 'haben',
    reflexive: false, separable: false, strong: false, objectCase: null, prepositions: [],
    example: { de: 'Was machst du heute?', en: 'What are you doing today?' }, level: 'A1' },
  { id: 's_v_004', type: 'verb', infinitive: 'kaufen', en: ['to buy'],
    conj: { ich: 'kaufe', du: 'kaufst', er: 'kauft', wir: 'kaufen', ihr: 'kauft', sie: 'kaufen' },
    perfekt: 'hat gekauft', praeteritum: 'kaufte', hilfsverb: 'haben',
    reflexive: false, separable: false, strong: false, objectCase: null, prepositions: [],
    example: { de: 'Ich kaufe ein neues Buch.', en: 'I am buying a new book.' }, level: 'A1' },
  { id: 's_v_005', type: 'verb', infinitive: 'kochen', en: ['to cook'],
    conj: { ich: 'koche', du: 'kochst', er: 'kocht', wir: 'kochen', ihr: 'kocht', sie: 'kochen' },
    perfekt: 'hat gekocht', praeteritum: 'kochte', hilfsverb: 'haben',
    reflexive: false, separable: false, strong: false, objectCase: null, prepositions: [],
    example: { de: 'Meine Mutter kocht jeden Abend.', en: 'My mother cooks every evening.' }, level: 'A1' },
  { id: 's_v_006', type: 'verb', infinitive: 'wohnen', en: ['to live (reside)'],
    conj: { ich: 'wohne', du: 'wohnst', er: 'wohnt', wir: 'wohnen', ihr: 'wohnt', sie: 'wohnen' },
    perfekt: 'hat gewohnt', praeteritum: 'wohnte', hilfsverb: 'haben',
    reflexive: false, separable: false, strong: false, objectCase: null, prepositions: [],
    example: { de: 'Wir wohnen in Zürich.', en: 'We live in Zurich.' }, level: 'A1' },
  { id: 's_v_007', type: 'verb', infinitive: 'arbeiten', en: ['to work'],
    conj: { ich: 'arbeite', du: 'arbeitest', er: 'arbeitet', wir: 'arbeiten', ihr: 'arbeitet', sie: 'arbeiten' },
    perfekt: 'hat gearbeitet', praeteritum: 'arbeitete', hilfsverb: 'haben',
    reflexive: false, separable: false, strong: false, objectCase: null, prepositions: [],
    example: { de: 'Er arbeitet bei einer Bank.', en: 'He works at a bank.' }, level: 'A1' },
  { id: 's_v_008', type: 'verb', infinitive: 'hören', en: ['to hear', 'to listen'],
    conj: { ich: 'höre', du: 'hörst', er: 'hört', wir: 'hören', ihr: 'hört', sie: 'hören' },
    perfekt: 'hat gehört', praeteritum: 'hörte', hilfsverb: 'haben',
    reflexive: false, separable: false, strong: false, objectCase: null, prepositions: [],
    example: { de: 'Ich höre gern Musik.', en: 'I like to listen to music.' }, level: 'A1' },
  { id: 's_v_009', type: 'verb', infinitive: 'sagen', en: ['to say', 'to tell'],
    conj: { ich: 'sage', du: 'sagst', er: 'sagt', wir: 'sagen', ihr: 'sagt', sie: 'sagen' },
    perfekt: 'hat gesagt', praeteritum: 'sagte', hilfsverb: 'haben',
    reflexive: false, separable: false, strong: false, objectCase: null, prepositions: [],
    example: { de: 'Was hast du gesagt?', en: 'What did you say?' }, level: 'A1' },
  { id: 's_v_010', type: 'verb', infinitive: 'fragen', en: ['to ask'],
    conj: { ich: 'frage', du: 'fragst', er: 'fragt', wir: 'fragen', ihr: 'fragt', sie: 'fragen' },
    perfekt: 'hat gefragt', praeteritum: 'fragte', hilfsverb: 'haben',
    reflexive: false, separable: false, strong: false, objectCase: null, prepositions: [],
    example: { de: 'Ich frage den Lehrer.', en: 'I am asking the teacher.' }, level: 'A1' },
  { id: 's_v_011', type: 'verb', infinitive: 'brauchen', en: ['to need'],
    conj: { ich: 'brauche', du: 'brauchst', er: 'braucht', wir: 'brauchen', ihr: 'braucht', sie: 'brauchen' },
    perfekt: 'hat gebraucht', praeteritum: 'brauchte', hilfsverb: 'haben',
    reflexive: false, separable: false, strong: false, objectCase: null, prepositions: [],
    example: { de: 'Ich brauche eine Pause.', en: 'I need a break.' }, level: 'A1' },

  /* ========== VERBS — A1 (strong/irregular common ones) ========== */
  { id: 's_v_012', type: 'verb', infinitive: 'sein', en: ['to be'],
    conj: { ich: 'bin', du: 'bist', er: 'ist', wir: 'sind', ihr: 'seid', sie: 'sind' },
    perfekt: 'ist gewesen', praeteritum: 'war', hilfsverb: 'sein',
    reflexive: false, separable: false, strong: true, objectCase: null, prepositions: [],
    example: { de: 'Ich bin müde.', en: 'I am tired.' }, level: 'A1' },
  { id: 's_v_013', type: 'verb', infinitive: 'haben', en: ['to have'],
    conj: { ich: 'habe', du: 'hast', er: 'hat', wir: 'haben', ihr: 'habt', sie: 'haben' },
    perfekt: 'hat gehabt', praeteritum: 'hatte', hilfsverb: 'haben',
    reflexive: false, separable: false, strong: true, objectCase: null, prepositions: [],
    example: { de: 'Hast du Zeit?', en: 'Do you have time?' }, level: 'A1' },
  { id: 's_v_014', type: 'verb', infinitive: 'gehen', en: ['to go', 'to walk'],
    conj: { ich: 'gehe', du: 'gehst', er: 'geht', wir: 'gehen', ihr: 'geht', sie: 'gehen' },
    perfekt: 'ist gegangen', praeteritum: 'ging', hilfsverb: 'sein',
    reflexive: false, separable: false, strong: true, objectCase: null, prepositions: [],
    example: { de: 'Ich gehe ins Kino.', en: 'I am going to the cinema.' }, level: 'A1' },
  { id: 's_v_015', type: 'verb', infinitive: 'kommen', en: ['to come'],
    conj: { ich: 'komme', du: 'kommst', er: 'kommt', wir: 'kommen', ihr: 'kommt', sie: 'kommen' },
    perfekt: 'ist gekommen', praeteritum: 'kam', hilfsverb: 'sein',
    reflexive: false, separable: false, strong: true, objectCase: null, prepositions: [],
    example: { de: 'Sie kommt aus Frankreich.', en: 'She comes from France.' }, level: 'A1' },
  { id: 's_v_016', type: 'verb', infinitive: 'fahren', en: ['to drive', 'to go (by vehicle)'],
    conj: { ich: 'fahre', du: 'fährst', er: 'fährt', wir: 'fahren', ihr: 'fahrt', sie: 'fahren' },
    perfekt: 'ist gefahren', praeteritum: 'fuhr', hilfsverb: 'sein',
    reflexive: false, separable: false, strong: true, objectCase: null, prepositions: [],
    example: { de: 'Wir fahren nach Berlin.', en: 'We are going to Berlin.' }, level: 'A1' },
  { id: 's_v_017', type: 'verb', infinitive: 'essen', en: ['to eat'],
    conj: { ich: 'esse', du: 'isst', er: 'isst', wir: 'essen', ihr: 'esst', sie: 'essen' },
    perfekt: 'hat gegessen', praeteritum: 'aß', hilfsverb: 'haben',
    reflexive: false, separable: false, strong: true, objectCase: null, prepositions: [],
    example: { de: 'Was isst du zum Frühstück?', en: 'What do you eat for breakfast?' }, level: 'A1' },
  { id: 's_v_018', type: 'verb', infinitive: 'trinken', en: ['to drink'],
    conj: { ich: 'trinke', du: 'trinkst', er: 'trinkt', wir: 'trinken', ihr: 'trinkt', sie: 'trinken' },
    perfekt: 'hat getrunken', praeteritum: 'trank', hilfsverb: 'haben',
    reflexive: false, separable: false, strong: true, objectCase: null, prepositions: [],
    example: { de: 'Ich trinke ein Glas Wasser.', en: 'I am drinking a glass of water.' }, level: 'A1' },
  { id: 's_v_019', type: 'verb', infinitive: 'lesen', en: ['to read'],
    conj: { ich: 'lese', du: 'liest', er: 'liest', wir: 'lesen', ihr: 'lest', sie: 'lesen' },
    perfekt: 'hat gelesen', praeteritum: 'las', hilfsverb: 'haben',
    reflexive: false, separable: false, strong: true, objectCase: null, prepositions: [],
    example: { de: 'Er liest jeden Abend ein Buch.', en: 'He reads a book every evening.' }, level: 'A1' },
  { id: 's_v_020', type: 'verb', infinitive: 'schreiben', en: ['to write'],
    conj: { ich: 'schreibe', du: 'schreibst', er: 'schreibt', wir: 'schreiben', ihr: 'schreibt', sie: 'schreiben' },
    perfekt: 'hat geschrieben', praeteritum: 'schrieb', hilfsverb: 'haben',
    reflexive: false, separable: false, strong: true, objectCase: null, prepositions: [],
    example: { de: 'Ich schreibe einen Brief.', en: 'I am writing a letter.' }, level: 'A1' },
  { id: 's_v_021', type: 'verb', infinitive: 'sprechen', en: ['to speak'],
    conj: { ich: 'spreche', du: 'sprichst', er: 'spricht', wir: 'sprechen', ihr: 'sprecht', sie: 'sprechen' },
    perfekt: 'hat gesprochen', praeteritum: 'sprach', hilfsverb: 'haben',
    reflexive: false, separable: false, strong: true, objectCase: null, prepositions: [],
    example: { de: 'Sie spricht drei Sprachen.', en: 'She speaks three languages.' }, level: 'A1' },
  { id: 's_v_022', type: 'verb', infinitive: 'sehen', en: ['to see'],
    conj: { ich: 'sehe', du: 'siehst', er: 'sieht', wir: 'sehen', ihr: 'seht', sie: 'sehen' },
    perfekt: 'hat gesehen', praeteritum: 'sah', hilfsverb: 'haben',
    reflexive: false, separable: false, strong: true, objectCase: null, prepositions: [],
    example: { de: 'Ich sehe einen Vogel.', en: 'I see a bird.' }, level: 'A1' },
  { id: 's_v_023', type: 'verb', infinitive: 'schlafen', en: ['to sleep'],
    conj: { ich: 'schlafe', du: 'schläfst', er: 'schläft', wir: 'schlafen', ihr: 'schlaft', sie: 'schlafen' },
    perfekt: 'hat geschlafen', praeteritum: 'schlief', hilfsverb: 'haben',
    reflexive: false, separable: false, strong: true, objectCase: null, prepositions: [],
    example: { de: 'Das Baby schläft tief.', en: 'The baby is sleeping deeply.' }, level: 'A1' },
  { id: 's_v_024', type: 'verb', infinitive: 'nehmen', en: ['to take'],
    conj: { ich: 'nehme', du: 'nimmst', er: 'nimmt', wir: 'nehmen', ihr: 'nehmt', sie: 'nehmen' },
    perfekt: 'hat genommen', praeteritum: 'nahm', hilfsverb: 'haben',
    reflexive: false, separable: false, strong: true, objectCase: null, prepositions: [],
    example: { de: 'Ich nehme den Bus.', en: 'I am taking the bus.' }, level: 'A1' },
  { id: 's_v_025', type: 'verb', infinitive: 'geben', en: ['to give'],
    conj: { ich: 'gebe', du: 'gibst', er: 'gibt', wir: 'geben', ihr: 'gebt', sie: 'geben' },
    perfekt: 'hat gegeben', praeteritum: 'gab', hilfsverb: 'haben',
    reflexive: false, separable: false, strong: true, objectCase: null, prepositions: [],
    example: { de: 'Er gibt mir ein Buch.', en: 'He is giving me a book.' }, level: 'A1' },

  /* ========== VERBS — Verbs with non-default object case (helfen+Dat etc.) ========== */
  { id: 's_v_026', type: 'verb', infinitive: 'helfen', en: ['to help'],
    conj: { ich: 'helfe', du: 'hilfst', er: 'hilft', wir: 'helfen', ihr: 'helft', sie: 'helfen' },
    perfekt: 'hat geholfen', praeteritum: 'half', hilfsverb: 'haben',
    reflexive: false, separable: false, strong: true, objectCase: 'Dat',
    prepositions: [{ prep: 'bei', case: 'Dat', meaning: 'with (a task)' }],
    example: { de: 'Ich helfe [verb|dat]dir[/] [bei|dat]der Hausaufgabe[/].', en: 'I am helping you with the homework.' }, level: 'A2' },
  { id: 's_v_027', type: 'verb', infinitive: 'gratulieren', en: ['to congratulate'],
    conj: { ich: 'gratuliere', du: 'gratulierst', er: 'gratuliert', wir: 'gratulieren', ihr: 'gratuliert', sie: 'gratulieren' },
    perfekt: 'hat gratuliert', praeteritum: 'gratulierte', hilfsverb: 'haben',
    reflexive: false, separable: false, strong: false, objectCase: 'Dat',
    prepositions: [{ prep: 'zu', case: 'Dat', meaning: 'on (occasion)' }],
    example: { de: 'Ich gratuliere [verb|dat]dir[/] [zu|dat]deinem Geburtstag[/].', en: 'I congratulate you on your birthday.' }, level: 'A2' },
  { id: 's_v_028', type: 'verb', infinitive: 'danken', en: ['to thank'],
    conj: { ich: 'danke', du: 'dankst', er: 'dankt', wir: 'danken', ihr: 'dankt', sie: 'danken' },
    perfekt: 'hat gedankt', praeteritum: 'dankte', hilfsverb: 'haben',
    reflexive: false, separable: false, strong: false, objectCase: 'Dat',
    prepositions: [{ prep: 'für', case: 'Akk', meaning: 'for' }],
    example: { de: 'Ich danke [verb|dat]dir[/] [für|akk]das Geschenk[/].', en: 'I thank you for the gift.' }, level: 'A2' },
  { id: 's_v_029', type: 'verb', infinitive: 'antworten', en: ['to answer', 'to reply'],
    conj: { ich: 'antworte', du: 'antwortest', er: 'antwortet', wir: 'antworten', ihr: 'antwortet', sie: 'antworten' },
    perfekt: 'hat geantwortet', praeteritum: 'antwortete', hilfsverb: 'haben',
    reflexive: false, separable: false, strong: false, objectCase: 'Dat',
    prepositions: [{ prep: 'auf', case: 'Akk', meaning: 'to (a question)' }],
    example: { de: 'Sie antwortet [verb|dat]mir[/] nicht.', en: "She doesn't answer me." }, level: 'A2' },
  { id: 's_v_030', type: 'verb', infinitive: 'gefallen', en: ['to please', 'to be liked by'],
    conj: { ich: 'gefalle', du: 'gefällst', er: 'gefällt', wir: 'gefallen', ihr: 'gefallt', sie: 'gefallen' },
    perfekt: 'hat gefallen', praeteritum: 'gefiel', hilfsverb: 'haben',
    reflexive: false, separable: false, strong: true, objectCase: 'Dat', prepositions: [],
    example: { de: 'Das Buch gefällt [verb|dat]mir[/] sehr.', en: 'I really like the book.' }, level: 'A2' },

  /* ========== VERBS — with prepositions (non-reflexive) ========== */
  { id: 's_v_031', type: 'verb', infinitive: 'warten', en: ['to wait'],
    conj: { ich: 'warte', du: 'wartest', er: 'wartet', wir: 'warten', ihr: 'wartet', sie: 'warten' },
    perfekt: 'hat gewartet', praeteritum: 'wartete', hilfsverb: 'haben',
    reflexive: false, separable: false, strong: false, objectCase: null,
    prepositions: [{ prep: 'auf', case: 'Akk', meaning: 'for' }],
    example: { de: 'Ich warte [auf|akk]den Bus[/].', en: 'I am waiting for the bus.' }, level: 'A2' },
  { id: 's_v_032', type: 'verb', infinitive: 'denken', en: ['to think'],
    conj: { ich: 'denke', du: 'denkst', er: 'denkt', wir: 'denken', ihr: 'denkt', sie: 'denken' },
    perfekt: 'hat gedacht', praeteritum: 'dachte', hilfsverb: 'haben',
    reflexive: false, separable: false, strong: true, objectCase: null,
    prepositions: [{ prep: 'an', case: 'Akk', meaning: 'about' }],
    example: { de: 'Ich denke oft [an|akk]meine Familie[/].', en: 'I often think about my family.' }, level: 'A2' },
  { id: 's_v_033', type: 'verb', infinitive: 'sprechen über', en: ['to talk about'],
    conj: { ich: 'spreche', du: 'sprichst', er: 'spricht', wir: 'sprechen', ihr: 'sprecht', sie: 'sprechen' },
    perfekt: 'hat gesprochen', praeteritum: 'sprach', hilfsverb: 'haben',
    reflexive: false, separable: false, strong: true, objectCase: null,
    prepositions: [{ prep: 'über', case: 'Akk', meaning: 'about' }, { prep: 'mit', case: 'Dat', meaning: 'with (someone)' }],
    example: { de: 'Wir sprechen [über|akk]die Politik[/].', en: 'We are talking about politics.' }, level: 'A2' },
  { id: 's_v_034', type: 'verb', infinitive: 'glauben', en: ['to believe'],
    conj: { ich: 'glaube', du: 'glaubst', er: 'glaubt', wir: 'glauben', ihr: 'glaubt', sie: 'glauben' },
    perfekt: 'hat geglaubt', praeteritum: 'glaubte', hilfsverb: 'haben',
    reflexive: false, separable: false, strong: false, objectCase: null,
    prepositions: [{ prep: 'an', case: 'Akk', meaning: 'in (something)' }],
    example: { de: 'Sie glaubt [an|akk]die Liebe[/].', en: 'She believes in love.' }, level: 'A2' },
  { id: 's_v_035', type: 'verb', infinitive: 'bitten', en: ['to ask (for)', 'to request'],
    conj: { ich: 'bitte', du: 'bittest', er: 'bittet', wir: 'bitten', ihr: 'bittet', sie: 'bitten' },
    perfekt: 'hat gebeten', praeteritum: 'bat', hilfsverb: 'haben',
    reflexive: false, separable: false, strong: true, objectCase: null,
    prepositions: [{ prep: 'um', case: 'Akk', meaning: 'for' }],
    example: { de: 'Er bittet [um|akk]Hilfe[/].', en: 'He is asking for help.' }, level: 'A2' },
  { id: 's_v_036', type: 'verb', infinitive: 'träumen', en: ['to dream'],
    conj: { ich: 'träume', du: 'träumst', er: 'träumt', wir: 'träumen', ihr: 'träumt', sie: 'träumen' },
    perfekt: 'hat geträumt', praeteritum: 'träumte', hilfsverb: 'haben',
    reflexive: false, separable: false, strong: false, objectCase: null,
    prepositions: [{ prep: 'von', case: 'Dat', meaning: 'about (dream)' }],
    example: { de: 'Ich träume oft [von|dat]meinem Urlaub[/].', en: 'I often dream about my vacation.' }, level: 'B1' },
  { id: 's_v_037', type: 'verb', infinitive: 'erzählen', en: ['to tell', 'to narrate'],
    conj: { ich: 'erzähle', du: 'erzählst', er: 'erzählt', wir: 'erzählen', ihr: 'erzählt', sie: 'erzählen' },
    perfekt: 'hat erzählt', praeteritum: 'erzählte', hilfsverb: 'haben',
    reflexive: false, separable: false, strong: false, objectCase: null,
    prepositions: [{ prep: 'von', case: 'Dat', meaning: 'about' }, { prep: 'über', case: 'Akk', meaning: 'about' }],
    example: { de: 'Sie erzählt [von|dat]ihrer Reise[/].', en: 'She is telling about her trip.' }, level: 'A2' },
  { id: 's_v_038', type: 'verb', infinitive: 'sich beschweren', en: ['to complain'],
    conj: { ich: 'beschwere mich', du: 'beschwerst dich', er: 'beschwert sich', wir: 'beschweren uns', ihr: 'beschwert euch', sie: 'beschweren sich' },
    perfekt: 'hat sich beschwert', praeteritum: 'beschwerte sich', hilfsverb: 'haben',
    reflexive: true, separable: false, strong: false, objectCase: null,
    prepositions: [{ prep: 'bei', case: 'Dat', meaning: 'to (someone)' }, { prep: 'über', case: 'Akk', meaning: 'about' }],
    example: { de: 'Ich möchte mich [bei|dat]dir[/] [über|akk]deinen Hund[/] beschweren.', en: 'I would like to complain to you about your dog.' }, level: 'B1' },

  /* ========== VERBS — Reflexive verbs ========== */
  { id: 's_v_039', type: 'verb', infinitive: 'sich freuen', en: ['to be glad', 'to look forward'],
    conj: { ich: 'freue mich', du: 'freust dich', er: 'freut sich', wir: 'freuen uns', ihr: 'freut euch', sie: 'freuen sich' },
    perfekt: 'hat sich gefreut', praeteritum: 'freute sich', hilfsverb: 'haben',
    reflexive: true, separable: false, strong: false, objectCase: null,
    prepositions: [{ prep: 'auf', case: 'Akk', meaning: 'about (future)' }, { prep: 'über', case: 'Akk', meaning: 'about (past/present)' }],
    example: { de: 'Ich freue mich [auf|akk]das Wochenende[/].', en: 'I am looking forward to the weekend.' }, level: 'A2' },
  { id: 's_v_040', type: 'verb', infinitive: 'sich interessieren', en: ['to be interested'],
    conj: { ich: 'interessiere mich', du: 'interessierst dich', er: 'interessiert sich', wir: 'interessieren uns', ihr: 'interessiert euch', sie: 'interessieren sich' },
    perfekt: 'hat sich interessiert', praeteritum: 'interessierte sich', hilfsverb: 'haben',
    reflexive: true, separable: false, strong: false, objectCase: null,
    prepositions: [{ prep: 'für', case: 'Akk', meaning: 'in' }],
    example: { de: 'Sie interessiert sich [für|akk]Kunst[/].', en: 'She is interested in art.' }, level: 'A2' },
  { id: 's_v_041', type: 'verb', infinitive: 'sich entscheiden', en: ['to decide'],
    conj: { ich: 'entscheide mich', du: 'entscheidest dich', er: 'entscheidet sich', wir: 'entscheiden uns', ihr: 'entscheidet euch', sie: 'entscheiden sich' },
    perfekt: 'hat sich entschieden', praeteritum: 'entschied sich', hilfsverb: 'haben',
    reflexive: true, separable: false, strong: true, objectCase: null,
    prepositions: [{ prep: 'für', case: 'Akk', meaning: 'for' }, { prep: 'gegen', case: 'Akk', meaning: 'against' }],
    example: { de: 'Wir entscheiden uns [für|akk]die rote Tür[/].', en: 'We decide on the red door.' }, level: 'B1' },
  { id: 's_v_042', type: 'verb', infinitive: 'sich erinnern', en: ['to remember'],
    conj: { ich: 'erinnere mich', du: 'erinnerst dich', er: 'erinnert sich', wir: 'erinnern uns', ihr: 'erinnert euch', sie: 'erinnern sich' },
    perfekt: 'hat sich erinnert', praeteritum: 'erinnerte sich', hilfsverb: 'haben',
    reflexive: true, separable: false, strong: false, objectCase: null,
    prepositions: [{ prep: 'an', case: 'Akk', meaning: 'about' }],
    example: { de: 'Ich erinnere mich [an|akk]unseren Urlaub[/].', en: 'I remember our vacation.' }, level: 'B1' },
  { id: 's_v_043', type: 'verb', infinitive: 'sich verlieben', en: ['to fall in love'],
    conj: { ich: 'verliebe mich', du: 'verliebst dich', er: 'verliebt sich', wir: 'verlieben uns', ihr: 'verliebt euch', sie: 'verlieben sich' },
    perfekt: 'hat sich verliebt', praeteritum: 'verliebte sich', hilfsverb: 'haben',
    reflexive: true, separable: false, strong: false, objectCase: null,
    prepositions: [{ prep: 'in', case: 'Akk', meaning: 'with' }],
    example: { de: 'Er verliebt sich [in|akk]sie[/].', en: 'He is falling in love with her.' }, level: 'B1' },
  { id: 's_v_044', type: 'verb', infinitive: 'sich kümmern', en: ['to take care'],
    conj: { ich: 'kümmere mich', du: 'kümmerst dich', er: 'kümmert sich', wir: 'kümmern uns', ihr: 'kümmert euch', sie: 'kümmern sich' },
    perfekt: 'hat sich gekümmert', praeteritum: 'kümmerte sich', hilfsverb: 'haben',
    reflexive: true, separable: false, strong: false, objectCase: null,
    prepositions: [{ prep: 'um', case: 'Akk', meaning: 'of' }],
    example: { de: 'Sie kümmert sich [um|akk]ihre Kinder[/].', en: 'She takes care of her children.' }, level: 'B1' },
  { id: 's_v_045', type: 'verb', infinitive: 'sich ärgern', en: ['to be annoyed', 'to get angry'],
    conj: { ich: 'ärgere mich', du: 'ärgerst dich', er: 'ärgert sich', wir: 'ärgern uns', ihr: 'ärgert euch', sie: 'ärgern sich' },
    perfekt: 'hat sich geärgert', praeteritum: 'ärgerte sich', hilfsverb: 'haben',
    reflexive: true, separable: false, strong: false, objectCase: null,
    prepositions: [{ prep: 'über', case: 'Akk', meaning: 'about' }],
    example: { de: 'Ich ärgere mich [über|akk]den Lärm[/].', en: 'I am annoyed about the noise.' }, level: 'B1' },
  { id: 's_v_046', type: 'verb', infinitive: 'sich treffen', en: ['to meet'],
    conj: { ich: 'treffe mich', du: 'triffst dich', er: 'trifft sich', wir: 'treffen uns', ihr: 'trefft euch', sie: 'treffen sich' },
    perfekt: 'hat sich getroffen', praeteritum: 'traf sich', hilfsverb: 'haben',
    reflexive: true, separable: false, strong: true, objectCase: null,
    prepositions: [{ prep: 'mit', case: 'Dat', meaning: 'with' }],
    example: { de: 'Wir treffen uns [mit|dat]Freunden[/].', en: 'We are meeting with friends.' }, level: 'A2' },

  /* ========== VERBS — Separable verbs ========== */
  { id: 's_v_047', type: 'verb', infinitive: 'anfangen', en: ['to begin', 'to start'],
    conj: { ich: 'fange an', du: 'fängst an', er: 'fängt an', wir: 'fangen an', ihr: 'fangt an', sie: 'fangen an' },
    perfekt: 'hat angefangen', praeteritum: 'fing an', hilfsverb: 'haben',
    reflexive: false, separable: true, strong: true, objectCase: null,
    prepositions: [{ prep: 'mit', case: 'Dat', meaning: 'with' }],
    example: { de: 'Ich fange [mit|dat]der Arbeit[/] an.', en: 'I am starting with the work.' }, level: 'A2' },
  { id: 's_v_048', type: 'verb', infinitive: 'aufhören', en: ['to stop', 'to cease'],
    conj: { ich: 'höre auf', du: 'hörst auf', er: 'hört auf', wir: 'hören auf', ihr: 'hört auf', sie: 'hören auf' },
    perfekt: 'hat aufgehört', praeteritum: 'hörte auf', hilfsverb: 'haben',
    reflexive: false, separable: true, strong: false, objectCase: null,
    prepositions: [{ prep: 'mit', case: 'Dat', meaning: 'with' }],
    example: { de: 'Er hört [mit|dat]dem Rauchen[/] auf.', en: 'He is stopping smoking.' }, level: 'A2' },
  { id: 's_v_049', type: 'verb', infinitive: 'einladen', en: ['to invite'],
    conj: { ich: 'lade ein', du: 'lädst ein', er: 'lädt ein', wir: 'laden ein', ihr: 'ladet ein', sie: 'laden ein' },
    perfekt: 'hat eingeladen', praeteritum: 'lud ein', hilfsverb: 'haben',
    reflexive: false, separable: true, strong: true, objectCase: null,
    prepositions: [{ prep: 'zu', case: 'Dat', meaning: 'to' }],
    example: { de: 'Ich lade dich [zu|dat]meiner Party[/] ein.', en: 'I am inviting you to my party.' }, level: 'A2' },
  { id: 's_v_050', type: 'verb', infinitive: 'teilnehmen', en: ['to participate', 'to take part'],
    conj: { ich: 'nehme teil', du: 'nimmst teil', er: 'nimmt teil', wir: 'nehmen teil', ihr: 'nehmt teil', sie: 'nehmen teil' },
    perfekt: 'hat teilgenommen', praeteritum: 'nahm teil', hilfsverb: 'haben',
    reflexive: false, separable: true, strong: true, objectCase: null,
    prepositions: [{ prep: 'an', case: 'Dat', meaning: 'in' }],
    example: { de: 'Sie nimmt [an|dat]dem Kurs[/] teil.', en: 'She is participating in the course.' }, level: 'B1' },

  /* ========== VERBS — More common A2/B1 ========== */
  { id: 's_v_051', type: 'verb', infinitive: 'verstehen', en: ['to understand'],
    conj: { ich: 'verstehe', du: 'verstehst', er: 'versteht', wir: 'verstehen', ihr: 'versteht', sie: 'verstehen' },
    perfekt: 'hat verstanden', praeteritum: 'verstand', hilfsverb: 'haben',
    reflexive: false, separable: false, strong: true, objectCase: null, prepositions: [],
    example: { de: 'Ich verstehe das Problem.', en: 'I understand the problem.' }, level: 'A2' },
  { id: 's_v_052', type: 'verb', infinitive: 'wissen', en: ['to know (a fact)'],
    conj: { ich: 'weiß', du: 'weißt', er: 'weiß', wir: 'wissen', ihr: 'wisst', sie: 'wissen' },
    perfekt: 'hat gewusst', praeteritum: 'wusste', hilfsverb: 'haben',
    reflexive: false, separable: false, strong: true, objectCase: null, prepositions: [],
    example: { de: 'Ich weiß die Antwort nicht.', en: "I don't know the answer." }, level: 'A2' },
  { id: 's_v_053', type: 'verb', infinitive: 'kennen', en: ['to know (be familiar with)'],
    conj: { ich: 'kenne', du: 'kennst', er: 'kennt', wir: 'kennen', ihr: 'kennt', sie: 'kennen' },
    perfekt: 'hat gekannt', praeteritum: 'kannte', hilfsverb: 'haben',
    reflexive: false, separable: false, strong: false, objectCase: null, prepositions: [],
    example: { de: 'Ich kenne diesen Film.', en: 'I know this film.' }, level: 'A2' },
  { id: 's_v_054', type: 'verb', infinitive: 'bleiben', en: ['to stay', 'to remain'],
    conj: { ich: 'bleibe', du: 'bleibst', er: 'bleibt', wir: 'bleiben', ihr: 'bleibt', sie: 'bleiben' },
    perfekt: 'ist geblieben', praeteritum: 'blieb', hilfsverb: 'sein',
    reflexive: false, separable: false, strong: true, objectCase: null, prepositions: [],
    example: { de: 'Wir bleiben zu Hause.', en: 'We are staying at home.' }, level: 'A2' },
  { id: 's_v_055', type: 'verb', infinitive: 'finden', en: ['to find'],
    conj: { ich: 'finde', du: 'findest', er: 'findet', wir: 'finden', ihr: 'findet', sie: 'finden' },
    perfekt: 'hat gefunden', praeteritum: 'fand', hilfsverb: 'haben',
    reflexive: false, separable: false, strong: true, objectCase: null, prepositions: [],
    example: { de: 'Ich finde den Schlüssel nicht.', en: "I can't find the key." }, level: 'A2' },
];

/* Expose for the app */
if (typeof window !== 'undefined') {
  window.SEED_CARDS = SEED_CARDS;
}
